
from enum import Enum
from typing import Any, Dict, Generator, List, Tuple, Optional, Union

### Third Party ###
from minimalmodbus import MODE_RTU, Instrument, NoResponseError, ModbusException
from serial import Serial, PARITY_NONE


class ErrorCodes(Enum):
    """
    Error codes, generated by the driver (Left: 0x20A5, Right: 0x20A6)
    """
    NO_ERROR = 0x0
    OVER_VOLTAGE = 0x1
    UNDER_VOLTAGE = 0x2 
    OVER_CURRENT = 0x4
    OVER_LOAD = 0x8
    CURRENT_OUT_OF_TOLERANCE = 0x10
    ENCODER_OUT_OF_TOLERANCE = 0x20
    VELOCITY_OUT_OF_TOLERANCE = 0x40
    REFERENCE_VOLTAGE_ERROR = 0x80
    EEPROM_ERROR = 0x100
    HALL_ERROR = 0x200
    MOTOR_OVER_TEMPERATURE = 0x400
    ENCODER_ERROR = 0x800
    DRIVER_OVER_TEMPERATURE = 0x1000
    GIVEN_SPEED_ERROR = 0x2000


class RS485Baud(Enum):
    B9600 = 6
    B19200 = 5
    B38400 = 4
    B57600 = 3
    B115200 = 2
    B128000 = 1


class CANBaud(Enum):
    B100 = 4
    B125 = 3
    B250 = 2
    B500 = 1
    B1000 = 0


class RPMSelector(Enum):
    _1_RPM = 0x1
    _1P5_RPM = 0x2
    _1P3_RPM = 0x3
    _1P4_RPM = 0x4
    _1P5_RPM = 0x5
    _1P6_RPM = 0x6
    _1P7_RPM = 0x7
    _1P8_RPM = 0x7
    _1P9_RPM = 0x9
    _1P10_RPM = 0xA


class ControlMode(Enum):
    Undefined = 0
    RelativePositionMode = 1
    AbsolutePositionMode = 2
    VelocityMode = 3
    TorqueMode = 4


class ControlWord(Enum):
    UNDEFINED = 0x0
    EMERGENCY_STOP = 0x05
    CLEAR_ERROR = 0x06
    STOP = 0x07
    ENABLE = 0x08
    START_SYNC = 0x10           # needed in position mode (Snc. mode)
    START_LEFT = 0x11           # needed in position mode
    START_RIGHT = 0x12          # needed in position mode


class ZLA8030D(Instrument):
    """Base class for driver.

    Parameters
    ----------
    portname : Union[str, Serial]
        Serial port path name.
    slave_address : int
        Slave address.
    baudrate : int, optional
        Baudrate, by default 57600
    logger : Optional[Logger]
        Logger object, root logger by default
    """

    ### ModbusRTU Commands ###
    _READ_COIL = 0x01
    """Modbus RTU command for reading coil"""
    _READ_INPUT = 0x02
    """Modbus RTU command for reading input"""
    _READ_HOLDING_REGISTER = 0x03
    """Modbus RTU command for reading holding register"""
    _READ_INPUT_REGISTER = 0x04
    """Modbus RTU command for reading input register"""
    _WRITE_COIL = 0x05
    """Modbus RTU command for writing coil"""
    _WRITE_HOLDING_REGISTER = 0x06
    """Modbus RTU command for writing holding register"""

    ### ERROR CODES ###
    _CODE_ILLEGAL_FUNCTION = 1
    _CODE_ILLEGAL_DATA_ADDRESS = 2
    _CODE_ILLEGAL_DATA_VALUE = 3
    _CODE_SLAVE_DEVICE_FAILURE = 4

    ### INPUT REGISTERS ### [READ ONLY]
    _INPUT_REGISTER_STATUS = 0x20A2
    """Driver controls motor movement: Left: bit7-bit6, Right: bit15-bit14:
            00 00:  Shaft release 
            00 40:  Shaft lock 
            00 80:  Emergency stop 
            00 C0:  Alarm

        Motor running status: Left: bit0, Right: bit8 
            0: Stop
            1: Run
    """
    _INPUT_REGISTER_DRIVER_TEMPERATURE = 0x20B0
    """I16 (SIGNED INT). Unit: 0.1°C; Range:-550~1200."""
    _INPUT_REGISTER_MOTOR_TEMPERATURE = 0x20A4
    """Unit: 1°C, Range:-55~120, Left: 8-15bits, Right: 0-7bits"""
    _INPUT_REGISTER_MOTOR_ERROR_CODE_LEFT = 0x20A5
    _INPUT_REGISTER_MOTOR_ERROR_CODE_RIGHT = 0x20A6
    """Driver error conditions defined by manufacturer.
            0x0000:     No error
            0x0001:     Over voltage
            0x0002:     Under voltage
            0x0004:     Overcurrent
            0x0008:     Overload
            0x0010:     Current out of tolerance(reserved)
            0x0020:     Encoder out of tolerance
            0x0040:     Velocity out of tolerance(reserved)
            0x0080:     Reference voltage error
            0x0100:     EEPROM error
            0x0200:     Hall error
            0x0400:     Motor temperature over temperature
            0x0800:     Encoder error
            0x1000:     high driver temperature
            0x2000:     Speed setting error(the given speed cannot exceedthe rated speed)
    """
    _INPUT_REGISTER_MOTOR_ACTUAL_VELOCITY_LEFT = 0x20AB
    _INPUT_REGISTER_MOTOR_ACTUAL_VELOCITY_RIGHT = 0x20AC
    """I16 (SIGNED INT). Actual velocity. Unit: 0.1RPM"""
    _INPUT_REGISTER_MOTOR_ACTUAL_TORQUE_LEFT = 0x20AD
    _INPUT_REGISTER_MOTOR_ACTUAL_TORQUE_RIGHT = 0x20AE
    """I16 (SIGNED INT). Actual torque. Unit: 0.1A"""

    ### HOLDING REGISTERS ###
# DRIVER PARAMETER
    _HOLDING_REGISTER_COMMUNICATION_OFFLINE_TIME = 0x2000
    """Driver and host communication offline time setting. Unit: ms, Range: 0-32767, Default: 0"""
    _HOLDING_REGISTER_RESTORE_FACTORY_SETTINGS = 0x2009
    """If value 1, restore factory settings."""
    _HOLDING_REGISTER_WRITE_TO_EEPROM = 0x2010
    """Whether the value of the communication write function codeis updatedtothe EEPROM. 0: Invalid, 1: Store parameters have RW attribution to EEPROM"""

    _HOLDING_REGISTER_RS485_NODE_ID = 0x2001
    """Slave address. Range 1-127, Default: 1"""
    _HOLDING_REGISTER_RS485_BAUD = 0x2002
    """RS485 BaudRate. Values: [6-9600, 5-19200, 4-38400, 3-57600, 2-115200, 1-128000], Default: 2"""

    _HOLDING_REGISTER_CAN_NODE_ID = 0x200A
    """Slave address. Range 1-127, Default: 1"""
    _HOLDING_REGISTER_CAN_BAUD = 0x200B
    """CAN BaudRate. Values: [4-100, 3-125, 2-250, 1-500, 0-1000], Default: 1"""


    _HOLDING_REGISTER_INPUT_SIGNAL_STATUS = 0x2003
    """2 input signal level status Bit0-Bit1: X0-X1 input level status. Read only"""
    _HOLDING_REGISTER_OUTPUT_SIGNAL_STATUS = 0x2004
    """2 output signal level status. Bit0: Y1 output status; Bit1-Bit2: B0-B1 output status. Read only"""
    _HOLDING_REGISTER_SHAFT_STATE_AFTER_POWER_ON = 0x2007
    """0: Not enabled, not lock shaft; 1: Not enabled, lock shaft;"""
    _HOLDING_REGISTER_MAX_MOTOR_SPEED = 0x2008
    """Motor maximum speed. Unit: r/min, Range: 1-1000r/min, Default: 300"""
    
    _HOLDING_REGISTER_PARKING_MODE = 0x200C
    """0: Close, 1: Open. Defaul: 0"""
    _HOLDING_REGISTER_CONTROL_MODE = 0x200D
    """0: Undefined, 1: Position mode (Relative), 2: Position mode (Absolute), 3: Velocity mode, 4: Torque mode. Default: 0"""
    _HOLDING_REGISTER_CONTROL_WORD = 0x200E
    """ 0x00:   Undefined 
        0x05:   Emergency stop 
        0x06:   Clear error 
        0x07:   Stop 
        0x08:   Enable 
        0x10:   Start(Synchronous)(needed inpositionmode) 
        0x11:   Start(Left) (needed in position mode) 
        0x12:   Start(Right) (needed in position mode)
    """
    _HOLDING_REGISTER_ENABLE_ASYNC_MODE = 0x200F
    """0: Synchronous mode, 1: Asynchronous mode. Default: 0"""
    _HOLDING_REGISTER_QUICK_STOP_MODE = 0x2011
    """How driver process when receive quick stop command. 5: Stop, 6: Quick stop (with deceleration time), 7: Quick stop (without deceleration time). Default: 5"""
    _HOLDING_REGISTER_CLOSE_OPERATION_MODE = 0x2012
    """How driver process when receive stop command. 0: Invalid, 1: Stop normally, switch to “ready to switch on” state. Default: 1"""
    _HOLDING_REGISTER_DISABLE_CONTROL_MODE = 0x2013
    """How driver process when receive disable command. 0: Invalid, 1: Stop (switch to “switch on” status). Default: 1"""
    _HOLDING_REGISTER_HALT_CONTROL_MODE = 0x2014
    """How driver process when receive Halt command. 1: Stop (operation enabled), 2: Quick stop with deceleration time (operation enable), 3: Quick stop without deceleration time (operation enable). Default: 1"""

    _HOLDING_REGISTER_INPUT_DEFAULT_LEVEL = 0x2016
    """Bit0: Input terminal X0, Bit1: Input terminal X1, Bit2: ADInput, Bit3-Bit5: reserved. 0: Default, 1: Reverse. The driver defaults to the input terminal level rising edge or high level active."""
    _HOLDING_REGISTER_X0_MODE = 0x2017
    """Input terminal X0 terminal function selection. 0: None, 1-8: NC, 9: Emergency STOP"""
    _HOLDING_REGISTER_X1_MODE = 0x2018
    """Input terminal X1 terminal function selection. 0: None, 1-8: NC, 9: Emergency STOP"""

    _HOLDING_REGISTER_OUTPUT_DEFAULT_LEVEL = 0x2019
    """Bit0: Output terminal Y1, Bit1: Output terminal B0, Bit2: Output terminal B1. 0: Default, 1: Reverse. The driver defaults to the input terminal level rising edge or high level active."""
    _HOLDING_REGISTER_B0_MODE = 0x201A
    """Output terminal B0 terminal function selection. 0: Open brake, 1: Close brake"""
    _HOLDING_REGISTER_B1_MODE = 0x201B
    """Output terminal B1 terminal function selection. 0: Open brake, 1: Close brake"""
    _HOLDING_REGISTER_Y1_MODE = 0x201B
    """Output terminal Y1 terminal function selection. 0: Undefined, 1: Alarm signal, 2: Drive status, Target position reached signal"""

    _HOLDING_REGISTER_DRIVER_TEMP_PROTECTION_THRESHOLD = 0x201E
    """Unit 0.1°C; Range: 0-1200. Defaut: 800"""
    _HOLDING_REGISTER_SPEED_RESOLUTION = 0x2022
    """1: 1 RPM, 2: 0.5 RPM, 3: 1/3 RPM 4: 0.25 RPM, 5: 0.2 RPM, 6: 1/6 RPM, 7: 1/7 RPM, 8: 0.125 RPM, 9: 1/9 RPM, A: 0.1RPM. Default: 1"""
    
    _HOLDING_REGISTER_REGEN_RES_VALUE = 0x2023
    """Regen resistance value. Unit 0.1Ω, Range 0-1000 (*0.1)"""
    _HOLDING_REGISTER_REGEN_RES_POWER = 0x2024
    """Regen resistance power. Unit W, Range 0-1000"""
    _HOLDING_REGISTER_REGEN_OPENING_VOLTAGE = 0x2025
    """Regen opening voltage . Unit 0.1V, Range 240-750 (*0.1). Default: 700"""
    _HOLDING_REGISTER_REGEN_CLOSE_VOLTAGE = 0x2026
    """Regen close voltage . Unit 0.1V, Range 240-750 (*0.1). Default: 620"""
    _HOLDING_REGISTER_REGEN_FUNC_CONTROL = 0x2027
    """Regen function control. Brake open/close. 0: close, 1: open. Default: 1"""

    _HOLDING_REGISTER_SPEED_EXCEEDS_TOLERANCE = 0x2028
    """0: close, 1: open. Default: 1"""
    _HOLDING_REGISTER_DEFAULT_DIRECTION = 0x2029
    """0: CW, 1: CCW. Default: 0"""

# CONTROL PARAMETER
    _HOLDING_REGISTER_S_SHAPE_ACCELERATION_LEFT = 0x2080
    _HOLDING_REGISTER_S_SHAPE_ACCELERATION_RIGHT = 0x2081
    _HOLDING_REGISTER_S_SHAPE_DECELERATION_LEFT = 0x2082
    _HOLDING_REGISTER_S_SHAPE_DECELERATION_RIGHT = 0x2083
    """Acceleration/Deceleration time Range: 0-32767ms. Default: 10"""
    _HOLDING_REGISTER_QUICK_STOP_DECELERATION_LEFT = 0x2084
    _HOLDING_REGISTER_QUICK_STOP_DECELERATION_RIGHT = 0x2085
    """Deceleration time Range: 0-32767ms. Default: 10"""

    _HOLDING_REGISTER_TARGET_VELOCITY_LEFT = 0x2088
    _HOLDING_REGISTER_TARGET_VELOCITY_RIGHT = 0x2089
    """Integer16 (SIGNED). Target velocity in velocity mode. Range: -3000 - 3000 RPM. Default: 0"""

    ### Bits ###
    _HIGH = 0x01
    _LOW = 0x00
